config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      sign_up: 'register'
  }

  resources :operations
  resources :people_sims
  resources :sim_cartes
  resources :addresses
  resources :people

end

app/models/sim_carte.rb
class SimCarte < ActiveRecord::Base
  default_scope { select(:numero, :status, :date_active) }

  has_many :people_sims
end

app/controllers/sim_cartes_controller.rb
class SimCartesController < ApplicationController
  before_action :set_sim_carte, only: [:show, :edit, :update, :destroy]

  # GET /sim_cartes
  # GET /sim_cartes.json
  def index
    @sim_cartes = SimCarte.all
  end

  # GET /sim_cartes/1
  # GET /sim_cartes/1.json
  def show
  end

  # GET /sim_cartes/new
  def new
    @sim_carte = SimCarte.new
  end

  # GET /sim_cartes/1/edit
  def edit
  end

  # POST /sim_cartes
  # POST /sim_cartes.json
  def create
    @sim_carte = SimCarte.new(sim_carte_params)

    respond_to do |format|
      if @sim_carte.save
        format.html { redirect_to @sim_carte, notice: 'Sim carte was successfully created.' }
        format.json { render :show, status: :created, location: @sim_carte }
      else
        format.html { render :new }
        format.json { render json: @sim_carte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sim_cartes/1
  # PATCH/PUT /sim_cartes/1.json
  def update
    respond_to do |format|
      if @sim_carte.update(sim_carte_params)
        format.html { redirect_to @sim_carte, notice: 'Sim carte was successfully updated.' }
        format.json { render :show, status: :ok, location: @sim_carte }
      else
        format.html { render :edit }
        format.json { render json: @sim_carte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sim_cartes/1
  # DELETE /sim_cartes/1.json
  def destroy
    @sim_carte.destroy
    respond_to do |format|
      format.html { redirect_to sim_cartes_url, notice: 'Sim carte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sim_carte
      @sim_carte = SimCarte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sim_carte_params
      params.require(:sim_carte).permit(:numero)
    end
end

app/helpers/sim_cartes_helper.rb
module SimCartesHelper
end

app/views/sim_cartes/_form.html.erb
<%= form_for(@sim_carte) do |f| %>
  <% if @sim_carte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sim_carte.errors.count, "error") %> prohibited this sim_carte from being saved:</h2>

      <ul>
      <% @sim_carte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sim_cartes/edit.html.erb
<h1>Editing Sim Carte</h1>

<%= render 'form' %>

<%= link_to 'Show', @sim_carte %> |
<%= link_to 'Back', sim_cartes_path %>

app/views/sim_cartes/index.html.erb
<h1>Listing Sim Cartes</h1>

<table class="table table-striped table-bordered table-condensed" id="sims">
  <thead>
    <tr class="color1">
      <th>Numero</th>
      <th>Status</th>
      <th>Date activation</th>
    </tr>
  </thead>

  <tbody>
    <% @sim_cartes.each do |sim_carte| %>
      <tr>
        <td><%= sim_carte.numero %></td>
        <td><%= sim_carte.status %></td>
        <td><%= sim_carte.date_active %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sim_cartes/new.html.erb
<h1>New Sim Carte</h1>

<%= render 'form' %>

<%= link_to 'Back', sim_cartes_path %>

app/views/sim_cartes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @sim_carte.numero %>
</p>

<%= link_to 'Edit', edit_sim_carte_path(@sim_carte) %> |
<%= link_to 'Back', sim_cartes_path %>