config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      sign_up: 'register'
  }

  resources :operations
  resources :people_sims
  resources :sim_cartes
  resources :addresses
  resources :people

end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TOUNKA', root_path, :class => "navbar-brand", id: "logo" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to ' ', root_path, class: "glyphicon glyphicon-home glyphiconhead", :title => "Home" %></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">SIM</a>
              <ul class="dropdown-menu">
                <li><%= link_to 'SIM Disponibles', sim_cartes_path %></li>
                <li><%= link_to 'SIM Attribues', people_sims_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'SIM Activés', sim_cartes_path %></li>
                <li><%= link_to 'SIM Desactivés', sim_cartes_path %></li>

              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle glyphicon glyphicon-eye-open glyphiconhead" data-toggle="dropdown"></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Opérations recents', operations_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Tiers</li>
                <li><%= link_to 'Customs', people_path %></li>

              </ul>
            </li>

        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle glyphicon glyphicon-user glyphiconhead" data-toggle="dropdown" , title="User"></a>
              <ul class="dropdown-menu">
                <li><%= link_to "#{current_user.role}", "#" %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% if current_user.role == 'Admin' %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle glyphicon glyphicon-wrench glyphiconhead" data-toggle="dropdown"></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'OUTILS', "#" %></li>
                  </ul>
                </li>
            <% end %>

        <% else %>
            <!--<li><%= link_to "Sign up", new_user_registration_path %></li>-->
            <li><%= link_to "", new_user_session_path(login_options), class: "glyphicon glyphicon-log-in glyphiconhead", :title => "Log in" %></li>
        <% end %>

      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<hr>
<div class="container">
  <%= yield %>
</div>

</body>
</html>