config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      sign_up: 'register'
  }

  resources :operations
  resources :people_sims
  resources :sim_cartes
  resources :addresses
  resources :people

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  belongs_to :people

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:number_owner, :number_sender, :type_op)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_owner %><br>
    <%= f.text_field :number_owner %>
  </div>
  <div class="field">
    <%= f.label :number_sender %><br>
    <%= f.text_field :number_sender %>
  </div>
  <div class="field">
    <%= f.label :type_op %><br>
    <%= f.text_field :type_op %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Operations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Number owner</th>
      <th>Number sender</th>
      <th>Type op</th>
      <th>Date op</th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.number_owner %></td>
        <td><%= operation.number_sender %></td>
        <td><%= operation.type_op %></td>
        <td><%= operation.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number owner:</strong>
  <%= @operation.number_owner %>
</p>

<p>
  <strong>Number sender:</strong>
  <%= @operation.number_sender %>
</p>

<p>
  <strong>Type op:</strong>
  <%= @operation.type_op %>
</p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>